### ISSUE TITLE
I have a small request (it is not issue it is just a request)

### ISSUE THREAD

**Issue by Aguastrike** [TiJ-code/Amtris#5]
Could you the kind Programmer pleas send me some money so my dead sick cat can have her surgery I only need like 200.000 $ and a diamond ring I hope you can help me 

Kind regards Obama

**Comment by TiJ-code** [comment]
> Could you the kind Programmer pleas send me some money so my dead sick cat can have her surgery I only need like 200.000 $ and a diamond ring I hope you can help me 
> 
> Kind regards Obama

How do I know you the real one?

**Comment by Aguastrike** [comment]
I hope nobody knows how many cocaine I get in a year

**Comment by Aguastrike** [comment]
> > Could you the kind Programmer pleas send me some money so my dead sick cat can have her surgery I only need like 200.000 $ and a diamond ring I hope you can help me
> > Kind regards Obama
> 
> How do I know you the real one?

Trust me bro

**Comment by TiJ-code** [comment]
> > > Could you the kind Programmer pleas send me some money so my dead sick cat can have her surgery I only need like 200.000 $ and a diamond ring I hope you can help me
> > > Kind regards Obama
> > 
> > How do I know you the real one?
> 
> Trust me bro

Send IBAN then

**Comment by Aguastrike** [comment]
Thank you for helping my issue and spending money on my problems I hope next time you crash your car

**Comment by TiJ-code** [comment]
> Thank you for helping my issue and spending money on my problems I hope next time you crash your car
Will do

Gonna hug a tree at 200km/h

**Comment by Aguastrike** [comment]
Ty for the help I don't think we should meet for the tuning but if you would be a 13 year old girl we could meet because of other reasons I'm also a 13 year old girl who is doing hobby horsing in her free time

**Comment by Aguastrike** [comment]
![IMG-20240924-WA0009](https://github.com/user-attachments/assets/5c58940f-7a57-447e-bf29-d9ebb61723df)
Des ist a Messer. Have fun!
